development:
  adapter: mysql2
  database: webttk
  username: root
  password: root
  encoding: utf8

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: webttk
  username: root
  password: chilibpi
  encoding: utf8
